server:
  port: 8081
  servlet:
    context-path: /myapp

spring:
    datasource:
      url: jdbc:mysql://localhost/bootdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username: root
      password:
      platform: mysql
    jpa:
      hibernate:
        ddl: create-drop